version: "2.0"

# Define the services/ containers to be run
services:
    
  web: # name of the second service
    build: . # specify the directory of the Dockerfile
    command: node index-db.js
    ports:
      - "3000:3000" #specify ports mapping
    links:
      - db
    environment: 
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass
      MYSQL_HOST: db
    
  db:
    image: orchardup/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass